runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /static
  static_dir: static

- url: /scripts
  static_dir: scripts

# put this after all other handlers
- url: /.*
  script: main.app


libraries:
- name: jinja2
  version: latest
